CREATE TABLE padaria_funcionarios (
	FUNC_ID int(11) AUTO_INCREMENT NOT NULL,
	FUNC_CARGO VARCHAR(30) NOT NULL,
	FUNC_NOME VARCHAR(30) NOT NULL,
	FUNC_SALARIO VARCHAR(30) NOT NULL,
	FUNC_CESTA VARCHAR(30) NOT NULL,
	FUNC_AJUDA VARCHAR(30) NOT NULL,
	FUNC_BONUS VARCHAR(30) NOT NULL,
	PRIMARY KEY(FUNC_ID)
);

CREATE TABLE padaria_cargos (
	CARGO_ID int(11) AUTO_INCREMENT NOT NULL,
	CARGO_NOME VARCHAR(30)	NOT NULL,
	CARGO_SALARIO VARCHAR(30) NOT NULL,
	PRIMARY KEY(CARGO_ID)
);

CREATE TABLE system_pages (
	PAGE_ID int(11) AUTO_INCREMENT NOT NULL,
	PAGE_NOME VARCHAR(30)NOT NULL,
	PAGE_URL VARCHAR(30)NOT NULL,
	PAGE_ROUTE VARCHAR(30)NOT NULL,
	PRIMARY KEY(PAGE_ID)
);
